# Generated by Django 3.2 on 2021-04-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength_score', models.PositiveSmallIntegerField()),
                ('dexterity_score', models.PositiveSmallIntegerField()),
                ('intelligence_score', models.PositiveSmallIntegerField()),
                ('constitution_score', models.PositiveSmallIntegerField()),
                ('wisdom_score', models.PositiveSmallIntegerField()),
                ('charisma_score', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
